#!/bin/bash
#SBATCH -N 1
#SBATCH -t 240:00:00
#SBATCH --ntasks 32
#SBATCH --ntasks-per-core 1
#SBATCH --partition=tc

module load 2022
module load ams/2023.101

echo "== Starting run at $(date)"
echo "== Job ID: ${SLURM_JOBID}"
echo "== Node list: ${SLURM_NODELIST}"
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}"
echo "== Scratch dir. : ${TMPDIR}"

BANDFRAG_DIRECTORY=~/BandFrag

# Slurmless testing parameters
# SLURM_JOB_NAME='jobtest'
# SLURM_SUBMIT_DIR=~/BandFrags
# AMSBIN="placeholder"

FRAGMENT_1_NAME="fragment_1"
FRAGMENT_2_NAME="fragment_2"
FRAGMENT_FULL_NAME="fragment_full"

$BANDFRAG_DIRECTORY/fragmenter.py $SLURM_SUBMIT_DIR <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

BandFrag
    IRC_path IRC_Forward.ams.amv
    strain_fragment_1 -19457.325
    strain_fragment_2 -1707.01

    fragment_mapping_1 1-93
    fragment_mapping_2 94-105

    bond_length 94 95 1.7531
End

AMS_JOBNAME=$FRAGMENT_1_NAME $AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_1_NAME.out

Task SinglePoint

System
    Atoms
FRAGMENT_1_XYZ
    End
    Lattice
FRAGMENT_1_LATTICES   
    End
End

Engine BAND
    Basis
        Type TZP
        Core None
    End
    
    Convergence
        Criterion 1.0e-6
    End
    
    NumericalQuality Good
    
    UseSymmetry No
    
    kspace
        Type regular
        Quality Good
    End

    XC
        GGA PBE
        DISPERSION GRIMME3 BJDAMP
    End
    
    Unrestricted No

EndEngine
eoj

cp $FRAGMENT_1_NAME.results/ams.rkf $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_1_NAME.ams.rkf
cp $FRAGMENT_1_NAME.results/band.rkf $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_1_NAME.band.rkf
cp $FRAGMENT_1_NAME.results/ams.log $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_1_NAME.log

##Single Point Calculation of Fragment 2 ##

AMS_JOBNAME=$FRAGMENT_2_NAME $AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_2_NAME.out

Task SinglePoint

System
    Atoms
FRAGMENT_2_XYZ
    End
    Lattice
FRAGMENT_2_LATTICES     
    End
End

Engine BAND
    Basis
        Type TZP
        Core None
    End
    
    Convergence
        Criterion 1.0e-6
    End
    
    NumericalQuality Good
    
    UseSymmetry No
    
    kspace
        Type regular
        Quality Good
    End

    XC
        GGA PBE
        DISPERSION GRIMME3 BJDAMP
    End
    
    Unrestricted No

EndEngine
eoj

cp $FRAGMENT_2_NAME.results/ams.rkf $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_2_NAME.ams.rkf
cp $FRAGMENT_2_NAME.results/band.rkf $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_2_NAME.band.rkf
cp $FRAGMENT_2_NAME.results/ams.log $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_2_NAME.log

## Periodic Energy Decomposition Analysis ##

AMS_JOBNAME=$FRAGMENT_FULL_NAME $AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_FULL_NAME.out

Task SinglePoint

System
    Atoms
FRAGMENT_FULL_XYZ
    End
    Lattice
FRAGMENT_FULL_LATTICE  
    End
End

Engine BAND
    Basis
        Type TZP
        Core None
    End
    
    Convergence
        Criterion 1.0e-6
    End
    
    NumericalQuality Good
    
    UseSymmetry No
    
    kspace
        Type regular
        Quality Good
    End

    XC
        GGA PBE
        DISPERSION GRIMME3 BJDAMP
    End
    
    Unrestricted No

   PEDA

   ## Fragment 1 ##
   Fragment
    filename $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_1_NAME.band.rkf
    AtomMapping
FRAGMENT_1_ATOM_MAPPING
    End
   End

   ## Fragment 2 ##
   Fragment
   filename $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_2_NAME.band.rkf
    AtomMapping
FRAGMENT_2_ATOM_MAPPING
    End
   End
EndEngine
eoj

# These can be incredibly large, and I do not recommend keeping these for every frame
# cp $FRAGMENT_FULL_NAME.results/ams.rkf $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_FULL_NAME.ams.rkf
# cp $FRAGMENT_FULL_NAME.results/band.rkf $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_FULL_NAME.band.rkf
cp $FRAGMENT_FULL_NAME.results/ams.log $SLURM_SUBMIT_DIR/FRAME_DIR/$FRAGMENT_FULL_NAME.log

rm -Rf $FRAGMENT_1_NAME.results $FRAGMENT_2_NAME.results $FRAGMENT_FULL_NAME.results

eor