#!/bin/bash
#SBATCH -N 1
#SBATCH -t 240:00:00
#SBATCH --ntasks 32
#SBATCH --ntasks-per-core 1
#SBATCH --partition=tc

module load 2022
module load ams/2023.101

echo "== Starting run at $(date)"
echo "== Job ID: ${SLURM_JOBID}"
echo "== Node list: ${SLURM_NODELIST}"
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}"
echo "== Scratch dir. : ${TMPDIR}"

BANDFRAG_DIRECTORY=~/BandFrag
# Slurmless testing parameters
# SLURM_JOB_NAME='jobtest'
# SLURM_SUBMIT_DIR=~/BandFrags
# AMSBIN="placeholder"

$BANDFRAG_DIRECTORY/fragmenter.py $SLURM_SUBMIT_DIR <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

BandFrag
    IRC_path IRC_Backward.ams.amv
    strain_fragment_1 5.056
    strain_fragment_2 2.05677

    fragment_mapping_1 1-80
    fragment_mapping_2 81-84

    bond_length 67 69 1.2
End

AMS_JOBNAME=Fragment_1 $AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/FRAME_DIR/Fragment_1.out

Task SinglePoint

System
    Atoms
FRAGMENT_1_XYZ
    End
    Lattice
FRAGMENT_1_LATTICES   
    End
End

Engine BAND
    Basis
        Type TZP
        Core None
    End
    
    Convergence
        Criterion 1.0e-6
    End
    
    NumericalQuality Good
    
    UseSymmetry No
    
    kspace
        Type regular
        Quality GammaOnly
    End

    XC
        GGA PBE
        DISPERSION GRIMME3 BJDAMP
    End
    
    Unrestricted No

EndEngine
eoj

##Single Point Calculation of Fragment 2 ##

AMS_JOBNAME=Fragment_2 $AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/FRAME_DIR/Fragment_2.out

Task SinglePoint

System
    Atoms
FRAGMENT_2_XYZ
    End
    Lattice
FRAGMENT_2_LATTICES     
    End
End

Engine BAND
    Basis
        Type TZP
        Core None
    End
    
    Convergence
        Criterion 1.0e-6
    End
    
    NumericalQuality Good
    
    UseSymmetry No
    
    kspace
        Type regular
        Quality GammaOnly
    End

    XC
        GGA PBE
        DISPERSION GRIMME3 BJDAMP
    End
    
    Unrestricted No

EndEngine
eoj

## Periodic Energy Decomposition Analysis ##

AMS_JOBNAME=pEDA $AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/FRAME_DIR/$SLURM_JOB_NAME.out

Task SinglePoint

System
    Atoms
FRAGMENT_FULL_XYZ
    End
    Lattice
FRAGMENT_FULL_LATTICE  
    End
End

Engine BAND
    Basis
        Type TZP
        Core None
    End
    
    Convergence
        Criterion 1.0e-6
    End
    
    NumericalQuality Good
    
    UseSymmetry No
    
    kspace
        Type regular
        Quality GammaOnly
    End

    XC
        GGA PBE
        DISPERSION GRIMME3 BJDAMP
    End
    
    Unrestricted No

   PEDA

   ## Fragment 1 ##
   Fragment
    filename $SLURM_SUBMIT_DIR/Fragment_1.band.rkf
    AtomMapping
FRAGMENT_1_ATOM_MAPPING
    End
   End

   ## Fragment 2 ##
   Fragment
   filename $SLURM_SUBMIT_DIR/Fragment_2.band.rkf
    AtomMapping
FRAGMENT_2_ATOM_MAPPING
    End
   End
EndEngine
eoj
eor
